pipeline{
        agent any
        environment {
            app_version = 'v1'
            rollback = 'false'
        }
        stages{
            stage('Build Image'){
                steps{
                    dir('jenkins-advanced-intergration-tutorial/chaperootodo_client') {
                    script{
                        if (env.rollback == 'false'){
                            image = docker.build("hivesp/chaperoo-frontend")
                        }
                    }}
                }
            }
            stage('Tag & Push Image'){
                steps{
                    script{
                        if (env.rollback == 'false'){
                            docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials'){
                                image.push("${env.app_version}")
                            }
                        }
                    }
                }
            }
            stage('Deploy Application'){
                steps{
                    dir('jenkins-advanced-intergration-tutorial/chaperootodo_client') {
                    sh "docker-compose pull && docker-compose up -d"
                }
            }}
        }
}